### ISSUE TITLE
How to set initial size for each Panel?

### ISSUE THREAD

**Issue by LUK3D** [Rudiksz/tabpanel#1]
## Hello! 
First of all, thanks for this awesome package. It'll help me a lot if you can tell me how to set the initial size for each tabs. I want to achieve this layout when the application starts.

## What I want:
![Screenshot 2022-01-28 231214](https://user-images.githubusercontent.com/31851972/151629010-664578b1-8bb0-44be-9cb4-8ef85243c49a.png)

## What I'm getting:
![Screenshot 2022-01-28 231128](https://user-images.githubusercontent.com/31851972/151629112-4283029b-a989-4e2e-b915-8630e5c1e3e0.png)

I have tried to do something like this:
```dart

 midlePanel.updateSize(0,DragUpdateDetails(globalPosition: Offset(379.0, 504.0)));

```
But sadly its not working.... ☹

**Comment by LUK3D** [comment]
I tried to fork the project and add some updates but unfortunately I don't work with mobx 😅

**Comment by Rudiksz** [comment]
Calling `updateSize` before the panels were built will have no effect.

https://pub.dev/documentation/tabpanel/latest/tabpanel/TabPanel-class.html
The TabPanel class has a panelSizes property that can be set using the constructor, but it accepts fixed width values. I think I added it in the constructor by reflex, because it is not intended to be used for initial sizing.

https://github.com/Rudiksz/tabpanel/blob/473d645168f9c1aaaaa432903cfc050788592d25/lib/src/tab_panel.dart#L230

Currently the space is divided equally between the tabs by default for simplicity.

Probably it would make more sense to have an `flex` property that would control the way children are sized, but that would require rewriting that line into a more sophisticated algorithm (or even adapt the one that the Flex widget uses).

**Comment by Rudiksz** [comment]
Try the new 0.2.3 version.
I updated the readme with an example that does exactly your layout.

Note that the new `flex` property is just for proportional sizing and it defaults to 1.
There is no mechanism to have fixed width panels because they are meant to be infinitely nestable and dynamic.

Let me know if you have any issues.

**Comment by Rudiksz** [comment]
Added a new version (0.2.4) with a `body` property for the panels, to set the widget to be displayed when it's empty.

This:
```dart
void main() async {
  // One initial panel
  // final tabPanel = TabPanel(defaultPage: YourDefaultPage());

  // or Create a more complex initial tab structure
  final tabPanel = TabPanel(
      defaultPage: PageA(),
      panels: [
        TabPanel(
          defaultPage: PageA(),
          panels: [],
          flex: 1,
        ),
        TabPanel(
          defaultPage: PageA(),
          axis: Axis.vertical,
          body: Container(color: Colors.blue),
          panels: [
            TabPanel(
              defaultPage: PageA(),
              panels: [],
              flex: 3,
              body: Container(color: Colors.green),
            ),
            TabPanel(
              defaultPage: PageA(),
              panels: [],
              flex: 1,
              body: Container(color: Colors.red),
            ),
          ],
          flex: 2,
        ),
        TabPanel(
          defaultPage: PageA(),
          panels: [],
          flex: 1,
        ),
      ],
    );

  runApp(
    MaterialApp(
      home: TabPanelWidget(tabPanel),
    ),
  );
}
```

Will give you this:
![image](https://user-images.githubusercontent.com/67291494/151662332-624cc098-442a-4945-b98d-9c38131b5d31.png)

**Comment by LUK3D** [comment]
> Try the new 0.2.3 version. I updated the readme with an example that does exactly your layout.
> 
> Note that the new `flex` property is just for proportional sizing and it defaults to 1. There is no mechanism to have fixed width panels because they are meant to be infinitely nestable and dynamic.
> 
> Let me know if you have any issues. 

Man, You are Awesome! 😁 Thank you very much!! 🙏
